In [1]:
import numpy as np
import matplotlib.pyplot as plt
from ase import build
from ase.visualize import view

In [2]:
atoms = build.graphene_nanoribbon(n=40,m=40,vacuum=10.0,sheet=True) # cria o sistema de grafeno, com célula unitária de 2 átomos. n e m multiplica a célula unitária em x e y

In [3]:
view(atoms)

<Popen: returncode: None args: ['c:\\Users\\yasmin24023\\.conda\\envs\\ase_e...>

In [4]:
# vira a célula para sair do eixo yz para xy

cell_array = atoms.cell.array
positions_array = atoms.get_positions()

print(cell_array)
print(positions_array)

new_cell_array = cell_array.copy()
new_cell_array[2,2] = cell_array[1,1]
new_cell_array[1,1] = cell_array[2,2]

new_positions = positions_array.copy()
new_positions[:,1] = positions_array[:,2]
new_positions[:,2] = positions_array[:,1]

graphene = atoms.copy()
graphene.set_cell(new_cell_array)
graphene.set_positions(new_positions)

[[85.2         0.          0.        ]
 [ 0.         20.          0.        ]
 [ 0.          0.         98.38048587]]
[[0.00000000e+00 1.00000000e+01 0.00000000e+00]
 [7.10000000e-01 1.00000000e+01 1.22975607e+00]
 [0.00000000e+00 1.00000000e+01 2.45951215e+00]
 ...
 [8.37800000e+01 1.00000000e+01 9.59209737e+01]
 [8.30700000e+01 1.00000000e+01 9.71507298e+01]
 [8.37800000e+01 1.00000000e+01 1.42108547e-14]]


In [5]:
#inserção de defeitos

natoms = len(graphene)
defect_percent = 10/100
ndefects = int(np.rint(defect_percent*natoms))
natoms,ndefects

(3200, 320)

In [6]:
defects_index = np.random.choice(np.arange(natoms),size=ndefects,replace=False)

In [7]:
defects_pos = graphene[defects_index]

In [8]:
defects_pos.write('graphene_defects_pos.poscar')

In [9]:
view(defects_pos)

<Popen: returncode: None args: ['c:\\Users\\yasmin24023\\.conda\\envs\\ase_e...>

In [10]:
graphene_defects = graphene.copy()
del graphene_defects[defects_index]

In [11]:
view(graphene_defects)

<Popen: returncode: None args: ['c:\\Users\\yasmin24023\\.conda\\envs\\ase_e...>

In [12]:
graphene_defects.write('graphene_defects.poscar')

In [13]:
with open('graphene_computem.xyz','w') as f:
    f.write('this line is comment\n')
    f.write(f'    {graphene_defects.cell.array[0,0]} {graphene_defects.cell.array[1,1]} {graphene_defects.cell.array[2,2]}\n')
    zvals = graphene_defects.get_atomic_numbers()
    positions = graphene_defects.get_positions()
    for io in range(len(graphene_defects)):
        f.write(f'   {zvals[io]:>2d}  {positions[io,0]:>9.6f}  {positions[io,1]:>9.6f}  {positions[io,2]:>9.6f}  1.0\n')
    f.write('   -1')